[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[phases.start]
cmd = "gunicorn dealer_project.wsgi:application --bind 0.0.0.0:${PORT}"
